export const testimonialdata = [
    {
        id: 1,
        heading: "The world's best and juiciest fruits.",
        image: "mockImage/Testimonialavtra1.png",
        bgImage:"mockImage/TestimonialBG1.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things - always super fresh goods and reliable delivery",
      },
      {
        id: 2,
        heading: "Super good products.",
        image: "mockImage/Testimonialavtra2.png",
        bgImage:"mockImage/TestimonialBG2.webp",
        name: "P.C. Reitveld",
        description: "Super good products, and last better than what is bought in the supermarket. The delivery is excellent, you recieve an SMS 20 minutes before delivery. Placed right at the door",
      },
      {
        id: 3,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra3.png",
        bgImage:"mockImage/TestimonialBG3.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 4,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra4.png",
        bgImage:"mockImage/TestimonialBG4.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 5,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra5.png",
        bgImage:"mockImage/TestimonialBG5.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 6,
        heading: "Super good products.",
        image: "mockImage/Testimonialavtra2.png",
        bgImage:"mockImage/TestimonialBG2.webp",
        name: "P.C. Reitveld",
        description: "Super good products, and last better than what is bought in the supermarket. The delivery is excellent, you recieve an SMS 20 minutes before delivery. Placed right at the door",
      },
      {
        id: 7,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra3.png",
        bgImage:"mockImage/TestimonialBG3.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 8,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra4.png",
        bgImage:"mockImage/TestimonialBG4.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 9,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra5.png",
        bgImage:"mockImage/TestimonialBG5.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 10,
        heading: "Super good products.",
        image: "mockImage/Testimonialavtra2.png",
        bgImage:"mockImage/TestimonialBG2.webp",
        name: "P.C. Reitveld",
        description: "Super good products, and last better than what is bought in the supermarket. The delivery is excellent, you recieve an SMS 20 minutes before delivery. Placed right at the door",
      },
      {
        id: 11,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra3.png",
        bgImage:"mockImage/TestimonialBG3.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      },
      {
        id: 12,
        heading: "Super god varer.",
        image: "mockImage/Testimonialavtra4.png",
        bgImage:"mockImage/TestimonialBG4.webp",
        name: "J. Skov",
        description: "The world's best and juiciest oranges and mandarins!!!! have also often bought super good avocados and tometoes and walnuts and pistachios and many other things",
      }
    ]